name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  ci-check:
    runs-on: ubuntu-latest
    name: Check CI
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn up
      - run: yarn ci:check
